---
bibliography: references.bib
---

# Discussion

Ce TFE a présenté les données de 26 patient·e·s transgenres suivi·e·s durant une durée médiane de six mois après initiation du THAG. Cet échantillon se compose d'une population jeune, dotée d'une grande mobilité géographique, aux besoins variés en termes de soins trans-affirmatifs et bénéficiant d'un bon soutien social en général. En outre, l'application des guidelines sur le THAG a permis d'obtenir des résultats satisfaisants au niveau des valeurs de laboratoire dans un contexte de médecine générale.

## Démographie

Près de la moitié des participant·e·s venaient d'une autre province que Liège alors que c'est là que j'exerce. Cette mobilité géographique naît du manque de professionnel·le·s formé·e·s et est décrite dans la littérature comme représentant une barrière au soin [@hostetter2022]. En particulier, certain·e·s participant·e·s venant du Hainaut mettaient près de deux heures en transports en commun pour se rendre en consultation. Devoir parcourir de telles distances pour avoir accès à des soins de santé n'est pas une situation enviable sur le plan de la santé publique.

Au niveau du statut à la mutuelle, `r sum(obj_demog_data$mutuelle == 'BIM')` des participant·e·s étaient BIM, soit plus du double de la moyenne wallonne de 21.5% [@ghesquiere2021]. Ces résultats sont cohérents avec des indicateurs d'une plus grande précarité au sein de la population des personnes transgenres, en raison des discriminations dont elles font l'objet. En Belgique, 30,8% des répondant·e·s du rapport de l'IEFH éprouvaient des difficultés financières à la fin du mois, contre une moyenne belge de 13.7% [@motmans2017].

Sur le plan administratif, le changement de prénom ou de marqueur de genre à l'état civil n'était pas systématique. En pratique, les médecins généralistes doivent donc être conscient·e·s que les documents officiels des patient·e·s ne reflètent pas nécessairement leur vécu. Il est donc nécessaire de leur demander comment iels préfèrent être genré·e·s et appelé·e·s en consultation. En outre, une conséquence pratique du changement de marqueur de genre est qu'il entraîne la création d'un nouveau numéro de registre national et la désactivation du précédent. De fait, en plus de quelques difficultés temporaires de communication avec les mutuelles, la totalité du dossier sur le Réseau Santé Wallon devient inaccessible au moment du changement.

Enfin, même si l'échantillon est insuffisant pour calculer une prévalence fiable, le fait que `r .N_dep` patient·e·s présentaient un trouble dépressif reste notable. Comme développé dans l'introduction, ces résultats sont cohérents avec la littérature scientifique [@witcomb2018].

## Soutien familial

Le soutien social était majoritairement bon au sein des participant·e·s de l'étude, même si `r .p_reac_neg` de patient·e·s ayant dû faire face à une réaction hostile de leur famille reste une valeur trop élevée. Ces chiffres doivent toutefois être relativisés en raison d'un facteur confondant essentiel. En effet, il existe une association forte entre le fait d'avoir du soutien parental et d'accéder au THAG chez les jeunes [@green2021]. Cet échantillon de patient·e·s transgenres jeunes ayant initié un THAG comporte donc vraisemblablement une surreprésentation de personnes ayant reçu du soutien parental. Vu la prévalence plus élevée de violences intrafamiliales [@wirtz2020], et l'importance du soutien familial pour la santé mentale ainsi que pour l'accès au THAG [@wang2021; @green2021], il doit s'agir d'un point d'attention dans l'esprit des généralistes. Sur cet aspect, la place particulière des médecins de famille peut être utilisée pour identifier des situations de non-acceptation voire de rejet, afin d'informer les parents et de soutenir les jeunes qui en sont victimes.

## Besoins et attentes en matière de soins trans-affirmatifs

### Traitement hormonal d'affirmation de genre

Les besoins et attentes en termes de traitement hormonal varient fortement d'une personne à l'autre et doivent donc être spécifiquement recherchés à l'anamnèse en vue de personnaliser le suivi et de refaire le point sur la satisfaction vis-à-vis des changements attendus. L'aggravation de la voix et le développement de la poitrine étaient les effets les plus attendus pour les personnes transmasculines et transféminines, respectivement. Cela peut se comprendre aisément au vu de l'importance sociale de ces deux éléments et, comme développé plus bas, la même logique s'applique pour les torsoplasties.

### Cryopréservation des gamètes

`r sum(subj_horm_data$cryo == '1')` patient·e·s transféminin·e·s avaient choisi d'entamer des procédures de préservation de la fertilité avant initiation du THAG. À mon plus grand mécontentement, le centre de procréation médicalement assistée d'un hôpital de la région a exprimé explicitement que la préservation de la fertilité des femmes transgenres était contraire à leur déontologie et qu'iels ne souhaitaient pas être impliqué·e·s dans ce type de projet familial. Outre la violence inouïe d'entendre ça en tant que patient·e, ce refus discriminatoire de soins illustre un aspect des barrières au soin présentées dans l'introduction. Le fait qu'aucune personne transmasculine n'ait choisi d'entamer ces démarches est lié à leur coût plus élevé ainsi qu'aux examens et traitements nécessaires, lesquels peuvent être difficiles à vivre pour les patient·e·s transmasculins [@moravek2018].

### Chirurgies d'affirmation de genre

La totalité des patient·e·s transmasculin·e·s de l'étude envisageait une torsoplastie ou réfléchissait encore à la question. Cette opération, visant à obtenir un torse plus masculin en retirant la poitrine, revêtait une importance particulière pour les patient·e·s. Effectivement, malgré une voix grave et un début de pilosité faciale, certain·e·s patient·e·s continuaient à se faire mégenrer dès lors que leur interlocuteur·ice devinait leur poitrine. Seul·e·s `r .p_hystero` des patient·e·s envisageaient une hystérectomie, des chiffres comparables aux 83,6% de répondant·e·s de l'IEFH qui déclaraient que l'hystérectomie n'était pas importante pour leur sentiment d'identité de genre [@motmans2017]. Certain·e·s endocrinologues belges continuent à exercer une pression sur les patient·e·s pour qu'une hystérectomie soit réalisée, argüant, en l'absence de toute preuve scientifique, qu'il existe un risque accru de cancer des ovaires ou de l'endomètre sous THAG masculinisant. Au vu de ces résultats, cette pratique apparaît comme d'autant plus inappropriée, vu que la majorité des personnes transmasculines n'aurait pas opté pour une telle opération de leur propre chef. Enfin, les opérations génitales (métadoïoplastie, phalloplastie) n'étaient envisagé·e·s par aucun·e patient·e de l'étude et sont effectivement plus rares [@motmans2017].

Chez les patient·e·s transféminin·e·s, la vaginoplastie et les chirurgies de féminisation faciale étaient les deux opérations les plus fréquemment envisagées. À la différence des personnes transmasculines, aucune personne transféminine n'avait vécu d'intervention chirurgicale d'affirmation de genre. Cela est sans doute lié au plus faible nombre de chirurgien·ne·s proposant ces opérations et une plus grande tendance des femmes transgenres à se rendre à l'étranger pour se faire opérer auprès de spécialistes qui leur inspirent davantage confiance [@motmans2017].

## Évolution des valeurs de laboratoire

### Les limites des intervalles de référence

Une des difficultés par rapport à l'interprétation des prises de sang est qu'il n'existe pas de consensus sur les intervalles à utiliser chez les personnes transgenres sous THAG [@sorelle2019]. Un bon exemple de cela est l'évaluation de la fonction rénale à travers le MDRD. En effet, cette formule dépend du taux de créatinine, de l'âge et est multipliée par 0.742 pour les femmes [@meulders2022] . Cela signifie que pour un même taux de créatinine, les femmes ont une fonction rénale calculée comme 25% inférieure à celle des hommes. En pratique, en revoyant une patiente pour la première fois après son changement de marqueur de genre, j'ai d'abord cru qu'elle faisait une insuffisance rénale aiguë en regardant sa fonction rénale à la prise de sang, avant de réaliser que sa créatinine n'avait pas augmenté et que la différence provenait du fait que le laboratoire utilisait désormais les formules dédiées aux femmes. Or, si les valeurs de créatine diminuent sous THAG féminisant, elles n'atteignent pas celles des femmes cisgenres [@greene2021]. Dans le même ordre d'idée, les patient·e·s sons THAG masculinisant ont une T~s~ comparable à celle des hommes cisgenres, mais une E2~s~ et une FSH plus élevées [@greene2021]. Les intervalles et formules employées par les laboratoire ne peuvent donc pas être suivis aveuglément et l'objectif d'obtenir des valeurs identiques à celles des personnes cisgenres mériterait sans doute d'être nuancé.

### Impact du THAG masculinisant sur les paramètres biologiques

Aucun test statistique n'ayant été utilisé pour le THAG féminisant, commentera uniquement les résultats du THAG masculinisant.

L'augmentation de l'hémoglobine, de l'hématocrite, de la créatinine et des transaminases hépatiques observées dans cet échantillon est confirmée par la littérature scientifique, de même que la diminution en HDL-C [@greene2021; @hashemi2021; @Velho2017].

### L'inhibition de l'axe hypothalamo-hypophyso-gonadique 

Peu importe le sexe, l'inhibition de l'axe HHG est produite par l'action des œstrogènes sur l'hypothalamus qui entraîne une diminution de la concentration en LH et FSH[@hall2019; @liu2019]. La production de testostérone étant stimulée par une action de la LH sur les testicules [@liu2019], on comprend aisément que les taux de testostérone augmentent lorsque la LH augmente dans la figure \@ref(fig:OutcomePlotF). En outre, le rôle inhibiteur de l'E2 explique également le fait que la LH diminue tandis que l'E2~s~ augmente. Toutefois, les valeurs de LH variaient fortement pour une même valeur d'E2~s~. Cette variabilité, combinée aux concentrations relativement élevées en E2~s~ nécessaires pour inhiber complètement l'axe HHG, explique sans doute qu'une relation directe entre la T~s~ et l'E2~s~ n'a pu être mise en évidence ici. On constate également sur ce graphique que la Spironolactone n'a pas d'influence notable sur l'axe HHG. En effet, lors de la combinaison E2 + Spironolactone, c'est bel et bien l'E2~s~ qui permet une diminution de la Ts [@angus2021]. Les T~s~ relativement élevées chez les patient·e·s prenant de la Spironolactone proviennent des valeurs d'E2s plus faibles (voir tableau \@ref(tab:OutcomeTableF)). Après discussion avec les patient·e·s en question lors d'une consultation de suivi, mon hypothèse sur cet E2~s~ bas réside en une application suboptimale du gel chez deux des patient·e·s. Elle ne pourra cependant pas être confirmée d'ici la publication de ce TFE. Pour les personnes sous THAG masculinisant, la situation est quelque peu différente. En effet, c'est la FSH qui stimule la production d'E2 par les ovaires [@hall2019] et c'est majoritairement l'aromatisation de la Ts en E2s qui permet d'inhiber la production de FSH[@liu2019]. Autrement dit, une relation linéaire décroissante où la l'E2~s~ diminue tandis que la T~s~ augmente, en miroir de ce qu'on observe sous THAG féminisant, n'est pas observée puisqu'il faut que la Ts se transforme en E2~s~ pour que la production endogène d'E2 diminue. En outre, la FSH ne dépend que partiellement de la stimulation de la GnRH, en comparaison avec la LH. De fait, une suppression complète de la GnRH n'entraîne une inhibition que de 40-60% de la FSH contre 90% de la LH [@hall2019]. Ces différents éléments pourraient permettre d'expliquer à la fois les valeurs plus élevées en FSH et en E2s que chez les hommes cisgenres ainsi que le fait que l'ovulation reste possible sous THAG masculinisant, bien que plus rare [@taub2020].

En pratique, pour les patient·e·s sous THAG féminisant présentant une Ts supérieure aux valeurs cibles des guidelines et pour lesquel·le·s il existe un inconfort vis-à-vis des effets de la Ts, le choix se portera entre une augmentation de la dose d'E2 pour inhiber l'axe, l'introduction de Spironolactone, comme antagoniste des effets de la Ts, ou l'introduction d'analogue de la GnRH comme le Depo-Eligard pour la supprimer. En l'absence de données fiables sur la meilleure décision à prendre, celle-ci devra mettre en balance les risques de TVP liés à l'E2 avec le coût des traitements et les préférences des patient·e·s. Pour les patient·e·s sous THAG, il est important de garder à l'esprit qu'une ovulation - et donc qu'une grossesse- restent possibles et une contraception adéquate doit être proposée, si nécessaire. En outre, le dosage de FSH/LH a moins d'intérêt clinique chez les patient·e·s transmasculin·e·s que chez les patient·e·s transféminin·e·s.

## Implications pour l'organisation des soins de santé

Le modèle standard, basé sur le diagnostic psychiatrique de dysphorie de genre, semble avoir encore moins de raison d'être, au vu des résultats de ce TFE. En effet, `r scales::percent(sum(obj_demog_data$adm_pren == '2')/(sum(obj_demog_data$adm_pren == '1')+sum(obj_demog_data$adm_pren == '2')))` et `r scales::percent(sum(obj_demog_data$adm_cec == '2')/(sum(obj_demog_data$adm_cec == '1')+sum(obj_demog_data$adm_cec == '2')))` des patient·e·s ayant changé respectivement de prénom et de marqueur de genre l'avaient fait avant initiation du THAG. Avant le 1^er^ janvier 2018, cela aurait été impossible puisque l'ancienne législation en vigueur prévoyait une approbation psychiatrique, un traitement hormonal, et une stérilisation pour accéder à ces changements administratifs [@servicepublicfederaldejustice2007]. L'État reconnaissant désormais aux individus le droit de déterminer librement leur identité, il n'y a, à mon sens, pas de place pour une évaluation psychiatrique préalablement à l'initiation d'un THAG. Sur quelle base peut-on, en effet, émettre des exigences que le législateur ne reconnait plus ? Si un accompagnement psychologique ou psychiatrique peut être utile durant la transition pour les personnes qui en font la demande, l'exiger comme condition préalable revient à s'opposer aux avancées législatives récentes. En outre, j'argüerai ici qu'un fonctionnement centralisé passant par des services spécialisés présente trois désavantages majeurs en termes de santé publique.

Premièrement, ces centres représentent des barrières supplémentaires dans l'accès au soin des personnes transgenres. En effet, avoir un nombre extrêmement réduit de professionnel·le·s aptes à prodiguer des soins trans-spécifiques a pour conséquences des temps d'attente souvent excessifs, la nécessité de parcourir des distances parfois importantes pour accéder à un·e médecin, et une monopolisation de l'offre de soin [@koehler2021]. Ce monopole se heurte à son tour au droit des patient·e·s de choisir librement leur médecin, dans la mesure où le nombre de professionnel·le·s est restreint. De surcroît, ces centres sont organisés comme de centres de soins ultraspécialisés appartenant à la troisième ligne de soins. Ce faisant, cette organisation même renforce l'idée qu'il s'agit d'une population exceptionnelle, présentant des besoins exceptionnels, concourant ainsi à la pathologisation des transidentités [@ker2021]. Il est important de distinguer ici la médicalisation, qui concerne les interventions de santé et traitements, et la pathologisation, qui se réfère au diagnostic des maladies [@ker2021]. La grossesse, par exemple, est un état presque toujours médicalisé (prises de sang, échographies, accouchement à l'hôpital, etc.), mais que nul ne considère comme pathologique. Or, les services hospitaliers peuvent être vus par les patient·e·s transgenres comme des endroits négatifs, où l'on est envoyé·e, plutôt qu'où l'on décide d'aller, et présentant des disparités de pouvoir importantes entre patient·e·s et spécialistes [@ker2021]. Enfin, je pense que reléguer les soins trans-spécifiques à la troisième ligne de soins contribue à déposséder les médecins des deux premières lignes de l'idée même qu'iels puissent développer des compétences qui paraissent, à tort, aussi complexes et spécialisées. Cette constatation m'a frappé lorsque j'ai référé un jour un homme transgenre à un endocrinologue pour des problèmes de surrénales sans lien aucun avec sa transidentité ou son THAG. Son premier réflexe a alors été de le référer à son tour vers l'endocrinologue du centre d'accompagnement des transidentités de Liège. Cette décision de sa part n'est cependant pas surprenante quand on prend en considération le fait que même les endocrinologues ne sont pas formé·e·s sur les transidentités ni sur le THAG [@irwig2016]. En outre, la même étude américaine a montré que moins d'un tiers des endocrinologues avait vu plus de cinq patient·e·s transgenres sur la totalité de sa carrière. Ce réflexe des deux premières lignes de soin à souvent se déclarer incompétent vis-à-vis des transidentités plutôt que de mobiliser des connaissances déjà présentes ou de chercher à se former découle, en partie, selon moi, de l'image d'exceptionnalité et de complexité qui touche les personnes transgenres et qui est renforcée par leur relégation à la troisième ligne de soins.

Pourtant, les patient·e·s transgenres sont en demande de soins de première ligne qui soient à la fois trans-affirmatifs et de qualité [@lee2022]. Améliorer la prise en charge de première ligne des personnes transgenres m'apparaît donc comme un enjeu important. De plus, une prise en charge trans-spécifique décentralisée en première ligne permet de favoriser l'accès au soin, le libre choix des médecins et des traitements, ainsi qu'une meilleure implication des médecins au sein de la communauté [@koehler2021].

## Forces et limitations du TFE

À ma connaissance, aucune étude présentant le résultat du suivi hormonal de patient·e·s transgenres en médecine générale n'a été publiée dans la littérature scientifique. Ce TFE est donc inédit et immédiatement utile aux médecins généralistes. En effet, plutôt que de proposer des informations provenant de contextes médicaux fort éloignés de la médecine générale, ces données proviennent directement de la première ligne. En outre, des recommandations pratiques sont disponibles dans les annexes afin d'assister les généralistes qui souhaiteraient à leur tour initier ou reprendre un THAG. De plus, un soin tout particulier a été apporté à la transparence et à la dissémination des résultats en publiant les scripts ayant permis l'élaboration du TFE ainsi qu'un site internet reprenant la totalité de son contenu. Malheureusement, ce travail n'est pas sans limitation. La première faiblesse réside dans la taille limitée de l'échantillon qui limite la confiance que l'on peut accorder aux résultats. Par ailleurs, la durée de suivi, en plus d'être inégale entre les patient·e·s, demeure globalement faible, notamment pour détecter des effets indésirables tels que des TVP. De plus, l'échantillon était majoritairement composé de personnes jeunes, vivant à Liège et référées via des associations, ce qui limite la généralisation des résultats. Enfin, la faiblesse principale réside en l'absence d'outcomes cliniques réellement pertinents comme la satisfaction des patient·e·s, l'amélioration de leur bien-être psychologique ou le développement de caractéristiques physiques importantes à leurs yeux. Si elle est inhérente au caractère rétrospectif de ce travail, et - hélas- habituelle dans la littérature scientifique sur le THAG, elle n'en demeure pas moins notable. Cela étant dit, malgré les limitations méthodologiques de ce TFE, les résultats présentés sont en conformité avec les données acquises dans des cohortes plus larges, témoignant ainsi de leur validité.

## Directions futures

L'étape suivante serait de mener une étude de cohorte prospective qui permettrait de mesurer les outcomes susmentionnés sur un plus grand nombre de patient·e·s, idéalement suivi·e·s pendant une durée minimale d'un an. La publication d'une telle étude dans une revue internationale à comité de lecture pourrait permettre de renforcer la légitimité bien réelle de la première ligne dans l'initiation du THAG tout en proposant des données utiles à un lectorat plus large.

\newpage
