# Conclusion

Les personnes transgenres représentent une population touchée par de nombreuses inégalités de santé qui se développent dans un contexte de discrimination et qui sont exacerbées par un mauvais accès au soin, à la fois dans ses versants généraux et trans-spécifiques. Parmi ces besoins de santé trans-spécifiques, le THAG représente souvent une nécessité et permet d'améliorer le bien-être des individus. Malheureusement, les barrières pour y accéder restent multiples et la structuration même des soins de santé en Belgique en fait partie.

En analysant les données de 26 patient·e·s transgenres dont j'ai initié le THAG en médecine générale, ce TFE contribue à montrer que l'instauration d'un THAG peut faire partie des compétences des médecins généralistes. En outre, en proposant des fiches pratiques à destination des soignant·e·s, il vise à promouvoir la formation des praticien·ne·s de première ligne dans ce domaine. En effet, la première ligne de soins possède des avantages notables pour les patient·e·s transgenres par rapport aux services hospitaliers, et augmenter le nombre de médecins formé·e·s sur les transidentités relève de l'enjeu de santé publique.

Permettre aux personnes transgenres d'accéder à des soins de qualité dans un cadre trans-affirmatif est une nécessité déontologique. Il s'agit également de la condition indispensable pour collaborer à l'amélioration de leur santé et participer à leur épanouissement.

\newpage
